### ISSUE TITLE
格式化结果不正确

### ISSUE THREAD

**Issue by sdaereew** [Tencent/BqLog#13]
for (int i = 0; i < 100; i++)
{
    g_pLog->info(u8"{}", i*1.0);
    g_pLog->info(u8"{:#010x}", i);
    g_pLog->info(u8"{:#x}", i);
}
以上代码输出如下:
![image](https://github.com/user-attachments/assets/1252c675-97ed-413f-895b-a140f0ad0b08)

**Comment by pippocao** [comment]
该issue应该在1.4.3已经修复了，对应的pull request为https://github.com/Tencent/BqLog/pull/11，您确认一下呢

**Comment by pippocao** [comment]
理解错了，我们修复一下

**Comment by pippocao** [comment]
fixed, try Release 1.4.4 please.

# Changelog
## [v1.4.4] - 2023-09-06
- **Improvement**: Add 2 tech articles to docs folder.
- **Bug fix**: Fix the bugs about `C++ 20 format`, Thanks the [issue report](https://github.com/Tencent/BqLog/issues/13) from [sdaereew](https://github.com/sdaereew).  Thanks to the contribution from [fkxingkong](https://github.com/fkxingkong), see [pull request](https://github.com/Tencent/BqLog/pull/17) and [pull request](https://github.com/Tencent/BqLog/pull/18).
