### ISSUE TITLE
中文路径导致创建日志文件失败

### ISSUE THREAD

**Issue by sdaereew** [Tencent/BqLog#37]
![image](https://github.com/user-attachments/assets/31a7de0f-623e-4ea6-a974-a097159a8e1c)
以上代码在debug版本能够正确运行,在release版本会出现创建日志失败.
![image](https://github.com/user-attachments/assets/2d79c943-f1ff-46a3-a443-a02fa38f39ee)

**Comment by sdaereew** [comment]
Windows 11 64, 版本1.4.7

**Comment by pippocao** [comment]
请详细描述一下，中文路径是指您的项目运行路径么？因为我看你的配置里没有中文。看输出猜测您的项目运行在中文路径下。
另外Debug和Release是指您用的bqLog的动态库是Debug或者Release的，还是说您的工程是Debug或者Release的

**Comment by sdaereew** [comment]
在中文路径运行. Debug版本连接Debug版本的日志库,release版本连接release版本的日志库.

**Comment by pippocao** [comment]
嗯，重现了，是setlocale(LC_ALL, "zh_CN.utf8");的问题，用了这一句之后，确实就出问题了

**Comment by pippocao** [comment]
fixed， please see main branch or tag Release 1.4.8

https://github.com/Tencent/BqLog/releases/tag/Release_1.4.8

[v1.4.8] - 2024-12-30
Bug fix: https://github.com/Tencent/BqLog/issues/37, resolving issues with paths exceeding 256 bytes on all platforms.
